### ISSUE TITLE
Sir i want to read data from Daly BMS but not get any response please help

### ISSUE THREAD

**Issue by PRADIPMAHAJAN** [ForrestFire0/GenericBMSArduino#3]
I am confused about the connection between Nodmcu and Daly BMS get data using UART and I don't have the proper code please help me give any code that access everything that I want please.

**Comment by ForrestFire0** [comment]
Daly BMS does not use the same UART protocol as the BMS's that this library is written for. This library will not work for a Daly BMS. The Daly BMS protocol can be found attached. I recommend using [Software Serial](https://www.arduino.cc/en/Reference/softwareSerial) in order to keep the hardware serial port free to communicate with the Serial Monitor. You must modify this library to utilize the Daly BMS protocol in order to use this library.
[Daly RS485+UART protocol.pdf](https://github.com/ForrestFire0/GenericBMSArduino/files/7106484/Daly.RS485%2BUART.protocol.pdf)
